name: eticket
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  geolocator: ^10.1.0
  get: 4.6.6
  http: 1.1.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  latlong: ^0.6.1
  location: ^5.0.3
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
